//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessFlex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Fees = new HashSet<Fee>();
            this.Attendances = new HashSet<Attendance>();
            
        }
    
        public int Id { get; set; }
       // public string Image = "GenderMale";
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Package { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<System.DateTime> DOE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fee> Fees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public static string SexConverter(bool booleanValue)
        {
            if (booleanValue) return 1.ToString();
            else return 0.ToString();
        }
       /* public void setImage()
        {
            if (Sex.Equals("1"))
            {
                Image = "GenderMale";

            }
            else
            {
                Image = "GenderFemale";
            }
        }*/
    }
}
